tfa.settings:
  type: config_object
  label: 'TFA settings'
  mapping:
    enabled:
      type: integer
      label: 'TFA enabled'
    time_skew:
     type: integer
     label: 'Number of 30 second chunks to allow TOTP keys between.'
    counter_window:
      type: integer
      label: 'How far ahead from current counter should we check the code.'
    recovery_codes_amount:
     type: integer
     label: 'Recovery codes amount. Default is 10.'
    name_prefix:
      type: string
      label: 'Prefix for OTP QR code names. Suffix is account username.'
    fallback_plugins:
      type: sequence
      label: 'Fallback plugins'
      sequence:
        type: fallback.config.[%key]
    setup_plugins:
      type: sequence
      label: 'TFA plugins'
    send_plugin:
      type: string
      label: 'Send plugins'
    login_plugins:
      type: mapping
      label: 'Enabled Login plugins'
      mapping:
        tfa_trusted_browser:
          type: string
          label: 'Tfa Trusted Browser'
    validate_plugin:
      type: string
      label: 'Current validation plugin'
    validation_skip:
      type: integer
      label: 'No. of times a user without tfa validation set-up can login.'
    encryption:
      type: string
      label: 'The id of the encrpytion profile.'
    trust_cookie_expiration:
      type: integer
      label: 'How long before TFA cookies expire. Default is 30 days.'
    cookie_name:
      type: string
      label: 'Cookie name of TFA trusted browser cookie. Default is "TB".'
    help_text:
      type: string
      label: 'Text to display on help page. Plain text only.'

default.fallback.config:
  type: mapping
  label: 'Default Fallback plugin config.'
  mapping:
    enable:
      type: integer
      label: 'Plugin state'
    weight:
      type: integer
      label: 'Weight'

default.fallback:
  type: mapping
  label: 'OTP Fallbacks'
  mapping:
    tfa_recovery_code:
      type: default.fallback.config
      label: 'Recovery code fallback'

fallback.config.*:
  type: default.fallback
  label: 'Fallback settings'